spring.application.name=messagequeue

server.port=${SERVER_PORT:8080}

broker.id=${BROKER_ID:1}
broker.host=${BROKER_HOST:localhost}

cluster.brokers=${CLUSTER_BROKERS:1:localhost:8081,2:localhost:8082,3:localhost:8083}